# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query_kosan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kosan', models.CharField(max_length=50)),
                ('alamat_kosan', models.CharField(max_length=100)),
                ('fasilitas', models.CharField(max_length=100)),
            ],
        ),
    ]
